import { getVisualColumns } from "../model/tableColumns";
import type { Cardinality, ColumnModel, DiagramModel, RelationModel, TableModel } from "../model/types";
import {
  createWikiBusinessRule,
  createWikiCustomSection,
  createWikiDocument,
  reconcileWikiDocument,
  type WikiDocument,
  type WikiFieldDocumentation,
  type WikiTableDocumentation,
} from "./wikiDocument";
import { DATA_DICTIONARY_END_MARKER, DATA_DICTIONARY_START_MARKER } from "./wikiGenerator";

export function generateWikiMarkdownFromDocument(diagram: DiagramModel, document: WikiDocument): string {
  const tableMap = new Map(diagram.tables.map((table) => [table.id, table]));
  const tableSections = diagram.tables.map((table) => {
    const documentation = findTableDocumentation(document, table);
    return generateTableSection(diagram, table, documentation, tableMap, document.options.includeRelationships);
  });
  const customSections = document.customSections
    .filter((section) => section.title.trim() || section.body.trim())
    .map((section) => [
      `# ${escapeHeading(section.title.trim() || "Seção sem título")}`,
      "",
      section.body.trim() || "_A documentar._",
    ].join("\n"));

  return compactBlankLines([
    `# ${escapeHeading(document.project.title.trim() || "Wiki do Projeto")}`,
    "",
    "| [Início](#início) | [Introdução](#introdução) | [Visão Geral](#visão-geral-do-banco-de-dados) | [Dicionário de Dados](#dicionário-de-dados) | [Conclusão](#conclusão) |",
    "| --- | --- | --- | --- | --- |",
    document.options.includeToc ? "\n_TOC_" : "",
    "",
    "# Início",
    "",
    document.project.summary.trim() || "_A documentar._",
    "",
    "# Introdução",
    "",
    document.project.introduction.trim() || "_A documentar._",
    "",
    "# Visão Geral do Banco de Dados",
    "",
    `O banco de dados possui **${diagram.tables.length} ${pluralize(diagram.tables.length, "tabela", "tabelas")}**, **${diagram.relations.length} ${pluralize(diagram.relations.length, "relacionamento", "relacionamentos")}** e **${diagram.enums.length} ${pluralize(diagram.enums.length, "enumeração", "enumerações")}**.`,
    "",
    document.project.overview.trim() || "_A documentar._",
    document.options.includeEnums ? generateEnumSummary(diagram) : "",
    "",
    DATA_DICTIONARY_START_MARKER,
    "# Dicionário de Dados",
    "",
    "> Estrutura técnica sincronizada com o diagrama; descrições e regras são mantidas pelo construtor da Wiki.",
    "",
    tableSections.length ? tableSections.join("\n\n") : "_O esquema ainda não possui tabelas para documentar._",
    DATA_DICTIONARY_END_MARKER,
    customSections.length ? `\n${customSections.join("\n\n")}` : "",
    "",
    "# Conclusão",
    "",
    document.project.conclusion.trim() || "_A documentar._",
    "",
  ].join("\n"));
}

export function migrateWikiMarkdown(
  markdown: string,
  diagram: DiagramModel,
  projectName: string,
): WikiDocument {
  const base = createWikiDocument(diagram, projectName);
  if (!markdown.trim()) return base;

  const sections = parseTopLevelSections(markdown);
  const knownNames = new Set(["inicio", "introducao", "visao geral do banco de dados", "dicionario de dados", "conclusao"]);
  const hasKnownStructure = sections.some((section) => knownNames.has(normalizeHeading(section.title))) ||
    markdown.includes(DATA_DICTIONARY_START_MARKER);
  if (!hasKnownStructure) {
    base.customSections = [{
      ...createWikiCustomSection("Conteúdo legado em Markdown"),
      body: markdown.trim(),
    }];
    return reconcileWikiDocument(base, diagram, projectName).document;
  }

  // Documents generated by DBML Studio always put the project title before
  // "Início". Identifying it by position (instead of by its text) also allows
  // projects and custom sections to use names such as "Introdução" safely.
  const start = findSection(sections, "inicio", { fromIndex: 1 });
  const titleSection = start ? sections[0] : sections.find((section) => !knownNames.has(normalizeHeading(section.title)));
  if (titleSection) base.project.title = unescapeMarkdown(titleSection.title).trim() || base.project.title;

  const introduction = findSection(sections, "introducao", { after: start });
  const overview = findSection(sections, "visao geral do banco de dados", { after: introduction ?? start });
  const dictionary = findSection(sections, "dicionario de dados", { after: overview ?? introduction ?? start });
  const conclusion = findSection(sections, "conclusao", { last: true });
  if (start) base.project.summary = cleanNarrative(start.body);
  if (introduction) base.project.introduction = cleanNarrative(introduction.body);
  if (overview) base.project.overview = cleanOverview(overview.body);
  if (conclusion) base.project.conclusion = cleanNarrative(conclusion.body);

  hydrateDictionary(base, markdown, diagram);

  const reservedSections = new Set(
    [titleSection, start, introduction, overview, dictionary, conclusion].filter(
      (section): section is TopLevelSection => Boolean(section),
    ),
  );
  const customSections = sections.filter((section) => !reservedSections.has(section));
  base.customSections = customSections.map((section) => ({
    ...createWikiCustomSection(unescapeMarkdown(section.title)),
    body: section.body.trim(),
  }));

  return reconcileWikiDocument(base, diagram, projectName).document;
}

export function getWikiColumnRestrictions(
  diagram: DiagramModel,
  table: TableModel,
  column: ColumnModel,
): string[] {
  const restrictions: string[] = [];
  const primaryIndexes = table.indexes.filter((index) => index.primary && index.columns.includes(column.name));
  const uniqueIndexes = table.indexes.filter((index) => index.unique && index.columns.includes(column.name));
  const references = diagram.relations.filter(
    (relation) => relation.fromTable === table.id && relation.fromColumn === column.name,
  );

  if (column.primaryKey || primaryIndexes.length) {
    const composite = primaryIndexes.find((index) => index.columns.length > 1);
    restrictions.push(composite ? `PK (${formatColumnList(composite.columns)})` : "PK");
  }
  if (references.length) {
    for (const relation of references) {
      const target = diagram.tables.find((item) => item.id === relation.toTable);
      restrictions.push(`FK → ${target?.name ?? relation.toTable}.${relation.toColumn}`);
    }
  } else if (column.foreignKey) restrictions.push("FK");
  if (!column.nullable) restrictions.push("NOT NULL");
  if (column.unique || uniqueIndexes.length) {
    const composite = uniqueIndexes.find((index) => index.columns.length > 1);
    restrictions.push(composite ? `UNIQUE (${formatColumnList(composite.columns)})` : "UNIQUE");
  }
  if (column.defaultValue !== undefined && column.defaultValue !== "") {
    restrictions.push(`DEFAULT ${column.defaultValue}`);
  }
  return restrictions;
}

export function getWikiTableRelationships(
  diagram: DiagramModel,
  table: TableModel,
): string[] {
  const tableMap = new Map(diagram.tables.map((item) => [item.id, item]));
  return diagram.relations
    .filter((relation) => relation.fromTable === table.id || relation.toTable === table.id)
    .map((relation) => formatRelationship(relation, table, tableMap));
}

function generateTableSection(
  diagram: DiagramModel,
  table: TableModel,
  documentation: WikiTableDocumentation | undefined,
  tableMap: Map<string, TableModel>,
  includeRelationships: boolean,
): string {
  const fieldDocs = documentation?.fields ?? [];
  const rows = getVisualColumns(table).map((column) => {
    const field = findFieldDocumentation(fieldDocs, column);
    const description = field?.description.trim() ? escapeTableCell(field.description) : "_A documentar._";
    const restrictions = getWikiColumnRestrictions(diagram, table, column);
    return `| \`${escapeInlineCode(column.name)}\` | \`${escapeInlineCode(column.type)}\` | ${description} | ${restrictions.length ? restrictions.map(formatRestrictionForMarkdown).join("<br>") : "—"} |`;
  });
  const relationships = diagram.relations.filter(
    (relation) => relation.fromTable === table.id || relation.toTable === table.id,
  );
  const rules = documentation?.businessRules.filter((rule) => rule.text.trim()) ?? [];

  return [
    `## ${escapeHeading(table.name)}`,
    "",
    documentation?.description.trim()
      ? formatBlockquote(documentation.description)
      : "> _Adicione uma descrição para explicar a responsabilidade desta tabela._",
    "",
    "| Campo | Tipo | Descrição | Restrição |",
    "| --- | --- | --- | --- |",
    ...(rows.length ? rows : ["| — | — | _Nenhum campo cadastrado._ | — |"]),
    includeRelationships ? "\n### Relacionamentos" : "",
    includeRelationships ? "" : "",
    ...(includeRelationships
      ? relationships.length
        ? relationships.map((relation) => formatRelationship(relation, table, tableMap))
        : ["_Nenhum relacionamento mapeado para esta tabela._"]
      : []),
    "",
    "### Regras de Negócio",
    "",
    ...(rules.length
      ? rules.map((rule) => `- ${rule.text.trim().replace(/\r?\n/g, "<br>")}`)
      : [`- [ ] Documentar as regras de negócio relacionadas à tabela \`${escapeInlineCode(table.name)}\`.`]),
  ].filter((line, index, lines) => line !== "" || lines[index - 1] !== "").join("\n");
}

function hydrateDictionary(document: WikiDocument, markdown: string, diagram: DiagramModel): void {
  const start = markdown.indexOf(DATA_DICTIONARY_START_MARKER);
  const end = markdown.indexOf(DATA_DICTIONARY_END_MARKER);
  if (start === -1 || end <= start) return;
  const dictionary = markdown.slice(start + DATA_DICTIONARY_START_MARKER.length, end);
  const matches = [...dictionary.matchAll(/^##\s+(.+)$/gm)];
  for (let index = 0; index < matches.length; index += 1) {
    const match = matches[index];
    const sectionEnd = matches[index + 1]?.index ?? dictionary.length;
    const rawSection = dictionary.slice(match.index, sectionEnd);
    const name = unescapeMarkdown(match[1].trim());
    const table = diagram.tables.find((item) => item.name.toLocaleLowerCase() === name.toLocaleLowerCase());
    const tableDoc = table ? findTableDocumentation(document, table) : undefined;
    if (!table || !tableDoc) {
      document.customSections.push({
        ...createWikiCustomSection(`Conteúdo legado: ${name}`),
        body: rawSection.trim(),
      });
      continue;
    }

    const fieldHeader = rawSection.indexOf("| Campo | Tipo | Descrição | Restrição |");
    if (fieldHeader > 0) {
      const beforeTable = rawSection.slice(rawSection.indexOf("\n") + 1, fieldHeader).trim();
      const description = cleanTableDescription(beforeTable);
      if (description) tableDoc.description = description;
    }

    for (const line of rawSection.split(/\r?\n/)) {
      const cells = splitMarkdownTableRow(line);
      if (!cells || cells.length !== 4 || !cells[0].startsWith("`")) continue;
      const fieldName = unwrapInlineCode(cells[0]);
      const field = table.columns.find((column) => column.name === fieldName);
      const fieldDoc = field ? findFieldDocumentation(tableDoc.fields, field) : undefined;
      if (!fieldDoc) continue;
      const description = cleanCellDescription(cells[2]);
      if (description) fieldDoc.description = description;
    }

    const rulesHeading = rawSection.indexOf("### Regras de Negócio");
    if (rulesHeading !== -1) {
      const rulesBlock = rawSection.slice(rulesHeading + "### Regras de Negócio".length);
      const rules = rulesBlock.split(/\r?\n/)
        .map((line) => line.match(/^\s*-\s+(.*)$/)?.[1]?.trim())
        .filter((line): line is string => typeof line === "string" && Boolean(line) && !/^\[ \] Documentar/.test(line));
      tableDoc.businessRules = rules.map((text) => ({ ...createWikiBusinessRule(), text: text.replace(/<br\s*\/?>/gi, "\n") }));
    }
  }
}

function findTableDocumentation(document: WikiDocument, table: TableModel): WikiTableDocumentation | undefined {
  return document.tables.find((item) => item.binding.sourceId === table.id) ??
    document.tables.find((item) => item.binding.name.toLocaleLowerCase() === table.name.toLocaleLowerCase());
}

function findFieldDocumentation(
  fields: WikiFieldDocumentation[],
  column: ColumnModel,
): WikiFieldDocumentation | undefined {
  return fields.find((field) => field.binding.sourceId === column.id) ??
    fields.find((field) => field.binding.name.toLocaleLowerCase() === column.name.toLocaleLowerCase());
}

function formatRelationship(
  relation: RelationModel,
  table: TableModel,
  tableMap: Map<string, TableModel>,
): string {
  const fromTable = tableMap.get(relation.fromTable)?.name ?? relation.fromTable;
  const toTable = tableMap.get(relation.toTable)?.name ?? relation.toTable;
  const fromEndpoint = `\`${escapeInlineCode(fromTable)}.${escapeInlineCode(relation.fromColumn)}\``;
  const toEndpoint = `\`${escapeInlineCode(toTable)}.${escapeInlineCode(relation.toColumn)}\``;
  const label = relation.label.trim() ? ` — ${escapeInline(relation.label.trim())}` : "";
  return relation.fromTable === table.id
    ? `- ${fromEndpoint} referencia ${toEndpoint} (${formatCardinality(relation.fromCardinality)} para ${formatCardinality(relation.toCardinality)})${label}.`
    : `- ${toEndpoint} é referenciado por ${fromEndpoint} (${formatCardinality(relation.toCardinality)} para ${formatCardinality(relation.fromCardinality)})${label}.`;
}

function generateEnumSummary(diagram: DiagramModel): string {
  if (!diagram.enums.length) return "";
  return [
    "## Enumerações",
    "",
    ...diagram.enums.map((item) => `- **${item.name}:** ${item.values.length ? item.values.map((value) => `\`${escapeInlineCode(value)}\``).join(", ") : "_sem valores cadastrados_"}`),
  ].join("\n");
}

interface TopLevelSection { title: string; body: string; start: number; }

function parseTopLevelSections(markdown: string): TopLevelSection[] {
  const headings = [...markdown.matchAll(/^#\s+(.+)$/gm)];
  return headings.map((heading, index) => ({
    title: heading[1].trim(),
    start: heading.index,
    body: markdown.slice((heading.index ?? 0) + heading[0].length, headings[index + 1]?.index ?? markdown.length).trim(),
  }));
}

function findSection(
  sections: TopLevelSection[],
  normalizedTitle: string,
  options: { after?: TopLevelSection; fromIndex?: number; last?: boolean } = {},
): TopLevelSection | undefined {
  const fromIndex = options.after ? sections.indexOf(options.after) + 1 : options.fromIndex ?? 0;
  const matches = sections.slice(Math.max(0, fromIndex))
    .filter((section) => normalizeHeading(section.title) === normalizedTitle);
  return options.last ? matches[matches.length - 1] : matches[0];
}

function cleanNarrative(value: string): string {
  const clean = value.replace(/<!--[^]*?-->/g, "").trim();
  return clean === "_A documentar._" ? "" : clean;
}

function cleanOverview(value: string): string {
  const clean = cleanNarrative(value)
    .replace(/^O banco de dados possui \*\*.*?\*\*\.\s*/s, "")
    .replace(/\n?## Enumerações[^]*$/i, "")
    .trim()
    .replace(/^Descreva aqui como os dados se organizam.*$/i, "");
  return clean === "_A documentar._" ? "" : clean;
}

function cleanTableDescription(value: string): string {
  const lines = value.split(/\r?\n/)
    .filter((line) => line.trim())
    .map((line) => line.replace(/^>\s?/, ""));
  const clean = lines.join("\n").trim();
  return /Adicione uma descrição para explicar/i.test(clean) ? "" : clean;
}

function cleanCellDescription(value: string): string {
  const clean = value.trim();
  return clean === "_A documentar._" ? "" : clean.replace(/\\\|/g, "|").replace(/<br\s*\/?>/gi, "\n");
}

function splitMarkdownTableRow(row: string): string[] | undefined {
  const trimmed = row.trim();
  if (!trimmed.startsWith("|") || !trimmed.endsWith("|")) return undefined;
  const cells: string[] = [];
  let current = "";
  let escaped = false;
  for (const character of trimmed.slice(1, -1)) {
    if (escaped) {
      current += `\\${character}`;
      escaped = false;
    } else if (character === "\\") {
      escaped = true;
    } else if (character === "|") {
      cells.push(current.trim());
      current = "";
    } else current += character;
  }
  cells.push(current.trim());
  return cells;
}

function unwrapInlineCode(value: string): string {
  return unescapeMarkdown(value.replace(/^`|`$/g, ""));
}

function normalizeHeading(value: string): string {
  return unescapeMarkdown(value).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase().trim();
}

function unescapeMarkdown(value: string): string {
  return value.replace(/\\([\\`*_{}\[\]<>#|])/g, "$1");
}

function formatBlockquote(value: string): string {
  return value.trim().split(/\r?\n/).map((line) => `> ${line}`).join("\n");
}

function escapeTableCell(value: string): string {
  return value.trim().replace(/\r?\n/g, "<br>").replace(/\|/g, "\\|");
}

function formatRestrictionForMarkdown(value: string): string {
  const foreignKey = value.match(/^FK → (.+)\.([^.]*)$/);
  if (foreignKey) {
    return `FK → \`${escapeInlineCode(foreignKey[1])}.${escapeInlineCode(foreignKey[2])}\``;
  }
  const defaultValue = value.match(/^DEFAULT (.*)$/s);
  if (defaultValue) return `DEFAULT \`${escapeInlineCode(defaultValue[1])}\``;
  return escapeTableCell(value);
}

function formatColumnList(columns: string[]): string {
  return columns.join(", ");
}

function escapeInline(value: string): string {
  return value.replace(/([\\`*_{}\[\]<>])/g, "\\$1").replace(/\r?\n/g, " ");
}

function escapeInlineCode(value: string): string {
  return String(value).replace(/`/g, "\\`").replace(/\r?\n/g, " ").replace(/\|/g, "\\|");
}

function escapeHeading(value: string): string {
  return value.replace(/\r?\n/g, " ").replace(/([\\`*_{}\[\]<>#])/g, "\\$1");
}

function formatCardinality(cardinality: Cardinality): string {
  return cardinality === "one" ? "um" : "muitos";
}

function pluralize(count: number, singular: string, plural: string): string {
  return count === 1 ? singular : plural;
}

function compactBlankLines(value: string): string {
  return `${value.replace(/\n{3,}/g, "\n\n").trim()}\n`;
}
