Table User {
  id uuid [pk]
  full_name String
  email String
  password String
  phone_number String
  birth_date datetime
  role Role
  plan_end_date DateTime
  streak Int
  coins Int
  createdAt DateTime
  enable Boolean
  desired_course String
  desired_exam String
  last_active DateTime
}

Table Exam {
  id uuid [pk]
  name String
  origin String
  image_url String
}

Table ExamDay {
  id uuid [pk]
  int day
  exam_id uuid
}

Table Attempt {
  id uuid [pk, fk]
  exam_id uuid
  user_id uuid
  time_spent_minutes Int
  score Int
  language Language
  init_time DateTime
  end_time DateTime
}

Table Attempt_day {
  id uuid [pk]
  time_spent_minutes Int
  current_question Int
  init_time DateTime
  end_time DateTime
  exam_day_id uuid
  attempt_id uuid
}

Table Subject {
  id uuid [pk]
  name String
}

Table Path {
  id uuid [pk]
  subject_id uuid
  name String
  text String
  schedule_position Int
  trail_position Int
}

Table StudyDay {
  id uuid [pk]
  user_id uuid
  day WeekDay
  hour Int
}

Table StudyLog {
  id uuid [pk]
  date DateTime
  done Boolean
  path_id uuid
  user_id uuid
}

Table Question {
  id uuid [pk]
  path_id uuid
  exam_day_id uuid
  text String
  origin Origin
  year Int
  feedback String
  number Int
  language Language
  image_url String
}

Table Alternative {
  id uuid [pk]
  text String
  letter char(1)
  is_correct Boolean
  question_id uuid
}

Table Answer {
  id uuid [pk]
  answer_date DateTime
  alternative_id uuid
  user_id uuid
  question_id uuid
  attempt_day_id uuid
}

Ref: Question.id > Answer.question_id

Ref: Question.id > Alternative.question_id

Ref: Answer.alternative_id > Alternative.id

Ref: Question.path_id > Path.id

Ref: Path.subject_id > Subject.id

Ref: StudyDay.user_id > User.id

Ref: StudyLog.user_id > User.id

Ref: StudyLog.path_id > Path.id

Ref: Question.exam_day_id > ExamDay.id

Ref: ExamDay.exam_id > Exam.id

Ref: Attempt.user_id > User.id

Ref: Attempt_day.exam_day_id > ExamDay.id

Ref: Attempt_day.attempt_id > Attempt.id

Ref: Answer.attempt_day_id > Attempt_day.id

Ref: User.id > Answer.user_id

Ref: Attempt.exam_id > Exam.id

Ref: Attempt_day.time_spent_minutes > Exam.image_url
