// @diagram
// background=#0f172a
// gridColor=#1f2a3a
// gridSize=4
// tableBackground=#111827
// tableBorder=#4b5f78
// tableHeader=#253142
// tableText=#e5edf7
// tableOpacity=1
// pkBadgeBackground=#3f2d12
// pkBadgeBorder=#f59e0b
// pkBadgeText=#fcd34d
// fkBadgeBackground=#12312e
// fkBadgeBorder=#2dd4bf
// fkBadgeText=#99f6e4
// notNullBadgeBackground=#3b1620
// notNullBadgeBorder=#fb7185
// notNullBadgeText=#fecdd3
// uniqueBadgeBackground=#1e1b4b
// uniqueBadgeBorder=#818cf8
// uniqueBadgeText=#c7d2fe
