// @diagram
// background=#0f172a
// gridColor=#1f2a3a
// gridSize=26
// tableBackground=#111827
// tableBorder=#4b5f78
// tableHeader=#253142
// tableText=#e5edf7
// tableLine=#94a3b8
// tableOpacity=1
// pkBadgeBackground=#3f2d12
// pkBadgeBorder=#f59e0b
// pkBadgeText=#fcd34d
// fkBadgeBackground=#12312e
// fkBadgeBorder=#2dd4bf
// fkBadgeText=#99f6e4
// notNullBadgeBackground=#3b1620
// notNullBadgeBorder=#fb7185
// notNullBadgeText=#fecdd3
// uniqueBadgeBackground=#1e1b4b
// uniqueBadgeBorder=#818cf8
// uniqueBadgeText=#c7d2fe

// @table ages_user
// x=156
// y=1430
// width=364
// height=262
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table ages_user {
  id uuid [pk]
  email varchar(255) [not null]
  pucrs_id char(8) [not null]
  name varchar(255) [not null]
  password varchar(255) [not null]
  image_url varchar(255)
  course course [not null]
  type user_type [not null]
}

// @table project
// x=1144
// y=2158
// width=364
// height=290
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table project {
  id uuid [pk]
  description text [not null]
  git_lab varchar(255)
  name varchar(255) [not null]
  active boolean [not null]
  group_photo_url varchar(255)
  year int [not null]
  semester semester [not null]
  logo_url varchar(255)
}

// @table team
// x=650
// y=2158
// width=364
// height=122
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table team {
  id uuid [pk]
  teacher_id uuid [not null]
  project_id uuid [not null]
}

// @table class
// x=650
// y=1820
// width=364
// height=206
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table class {
  id uuid [pk]
  number int [not null]
  year int [not null]
  semester semester [not null]
  teacher_id uuid [not null]
  active boolean [not null]
}

// @table semester_profile
// x=650
// y=1430
// width=364
// height=234
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table semester_profile {
  id uuid [pk]
  grade numeric(4,2)
  ages_role ages_role [not null]
  student_status semester_status [not null]
  user_id uuid [not null]
  team_id uuid [not null]
  class_id uuid [not null]
}

// @table lesson
// x=1144
// y=1820
// width=364
// height=122
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table lesson {
  id uuid [pk]
  date timestamp [not null]
  class_id uuid [not null]
}

// @table otp
// x=156
// y=1820
// width=364
// height=178
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table otp {
  id uuid [pk]
  user_id uuid [not null]
  expires_at timestamp [not null]
  token varchar(255) [not null]
  used boolean [not null]
}

// @table schedule
// x=156
// y=2158
// width=364
// height=206
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table schedule {
  id uuid [pk]
  admin_id uuid [not null]
  event char(10) [not null]
  event_date timestamp [not null]
  event_period char(10) [not null]
  event_time time(0) [not null]
}

// @table technology
// x=1638
// y=2314
// width=364
// height=122
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table technology {
  id uuid [pk]
  name varchar(255) [not null]
  type technology_type [not null]
}

// @table project_stack
// x=1638
// y=2158
// width=364
// height=122
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table project_stack {
  id uuid [pk]
  project_id uuid [not null]
  technology_id uuid [not null]
  indexes {
    (project_id, technology_id) [unique]
  }
}

// @table report
// x=1144
// y=1430
// width=364
// height=234
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table report {
  id uuid [pk]
  student_id uuid [not null]
  create_date timestamp [not null]
  edit_date timestamp [not null]
  grade numeric(4,2)
  type report_type [not null]
  url_archive varchar(255)
}

// @table examining_board
// x=650
// y=1118
// width=364
// height=178
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table examining_board {
  id uuid [pk]
  date date [not null]
  grade numeric(4,2) [not null]
  room varchar(255) [not null]
  student_id uuid [not null]
}

// @table examining_board_member
// x=156
// y=1118
// width=364
// height=122
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table examining_board_member {
  id uuid [pk]
  examining_board_id uuid [not null]
  teacher_id uuid [not null]
}

// @table attendance
// x=1638
// y=1820
// width=364
// height=122
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table attendance {
  id uuid [pk]
  lesson_id uuid [not null]
  student_id uuid [not null]
}

// @table report_review
// x=1144
// y=1118
// width=364
// height=178
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table report_review {
  id uuid [pk]
  comment text [not null]
  correction_url varchar(255) [not null]
  revision_date timestamp [not null]
  report_id uuid [not null]
}

// @table sprint_report
// x=1638
// y=1430
// width=364
// height=262
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table sprint_report {
  id uuid [pk]
  activity_completed text [not null]
  learned_lessons text [not null]
  next_steps text [not null]
  predicted_activity text [not null]
  problems_encountered text [not null]
  sprint sprint [not null]
  report_id uuid [not null, unique]
}

// @table hours_report
// x=1638
// y=1118
// width=364
// height=234
// useDefaultStyle=false
// useGroupStyle=true
// background=#111827
// border=#4b5f78
// header=#253142
// text=#e5edf7
// line=#94a3b8
// opacity=1
Table hours_report {
  id uuid [pk]
  activities text
  entry_time timestamp [not null]
  exit_time timestamp
  rejection_justification text
  approved boolean [not null]
  report_id uuid [not null, unique]
}

Ref: ages_user.id > team.teacher_id
// @line relation-ages_user-id-team-teacher_id-0
// color=#94a3b8
// useTableLineColor=true
// strokeWidth=2
// opacity=0.9
// style=solid
// route=orthogonal
// from=east
// to=west
// fromCardinality=many
// toCardinality=one

Ref: team.project_id > project.id
// @line relation-team-project_id-project-id-1
// color=#0E7490
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=east
// to=west
// fromCardinality=one
// toCardinality=one

Ref: ages_user.id > class.teacher_id
// @line relation-ages_user-id-class-teacher_id-2
// color=#94a3b8
// useTableLineColor=true
// strokeWidth=2
// opacity=0.9
// style=solid
// route=orthogonal
// from=east
// to=west
// fromCardinality=many
// toCardinality=one

Ref: ages_user.id > semester_profile.user_id
// @line relation-ages_user-id-semester_profile-user_id-3
// color=#94a3b8
// useTableLineColor=true
// strokeWidth=2
// opacity=0.9
// style=solid
// route=orthogonal
// from=east
// to=west
// fromCardinality=many
// toCardinality=one

Ref: team.id > semester_profile.team_id
// @line relation-team-id-semester_profile-team_id-4
// color=#94a3b8
// useTableLineColor=true
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=west
// to=west
// fromCardinality=many
// toCardinality=one
// via=(624,2210),(624,1622)

Ref: class.id > semester_profile.class_id
// @line relation-class-id-semester_profile-class_id-5
// color=#94a3b8
// useTableLineColor=true
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=east
// to=east
// fromCardinality=many
// toCardinality=one
// via=(1046,1872),(1046,1650)

Ref: lesson.class_id > class.id
// @line relation-lesson-class_id-class-id-6
// color=#047857
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=west
// to=east
// fromCardinality=many
// toCardinality=one

Ref: otp.user_id > ages_user.id
// @line relation-otp-user_id-ages_user-id-7
// color=#1D4ED8
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=west
// to=west
// fromCardinality=many
// toCardinality=one
// via=(130,1482)

Ref: schedule.admin_id > ages_user.id
// @line relation-schedule-admin_id-ages_user-id-8
// color=#1D4ED8
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=west
// to=west
// fromCardinality=many
// toCardinality=one
// via=(130,1482)

Ref: project_stack.project_id > project.id
// @line relation-project_stack-project_id-project-id-9
// color=#0E7490
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=west
// to=east
// fromCardinality=many
// toCardinality=one
// via=(1606,2238),(1540,2238),(1540,2210)

Ref: project_stack.technology_id > technology.id
// @line relation-project_stack-technology_id-technology-id-10
// color=#0E7490
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=west
// to=west
// fromCardinality=many
// toCardinality=one
// via=(1580,2240),(1580,2340)

Ref: report.student_id > semester_profile.id
// @line relation-report-student_id-semester_profile-id-11
// color=#1D4ED8
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=west
// to=east
// fromCardinality=many
// toCardinality=one
// via=(1112,1510),(1046,1510),(1046,1482)

Ref: examining_board.student_id > semester_profile.id
// @line relation-examining_board-student_id-semester_profile-id-12
// color=#1D4ED8
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=west
// to=west
// fromCardinality=one
// toCardinality=one
// via=(624,1482)

Ref: examining_board_member.examining_board_id > examining_board.id
// @line relation-examining_board_member-examining_board_id-examining_board-id-13
// color=#7E22CE
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=east
// to=west
// fromCardinality=many
// toCardinality=one

Ref: examining_board_member.teacher_id > ages_user.id
// @line relation-examining_board_member-teacher_id-ages_user-id-14
// color=#1D4ED8
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=west
// to=west
// fromCardinality=many
// toCardinality=one
// via=(130,1226),(130,1482)

Ref: attendance.lesson_id > lesson.id
// @line relation-attendance-lesson_id-lesson-id-15
// color=#047857
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=west
// to=east
// fromCardinality=many
// toCardinality=one
// via=(1580,1900),(1560,1872),(1514,1872)

Ref: attendance.student_id > semester_profile.id
// @line relation-attendance-student_id-semester_profile-id-16
// color=#1D4ED8
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=east
// to=east
// fromCardinality=many
// toCardinality=one
// via=(2028,1716),(1612,1716),(1118,1612),(1046,1482)

Ref: report_review.report_id > report.id
// @line relation-report_review-report_id-report-id-17
// color=#B45309
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=west
// to=west
// fromCardinality=one
// toCardinality=one
// via=(1118,1482)

Ref: sprint_report.report_id > report.id
// @line relation-sprint_report-report_id-report-id-18
// color=#B45309
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=west
// to=east
// fromCardinality=one
// toCardinality=one
// via=(1580,1678),(1586,1482),(1514,1482)

Ref: hours_report.report_id > report.id
// @line relation-hours_report-report_id-report-id-19
// color=#B45309
// useTableLineColor=false
// strokeWidth=4
// opacity=0.9
// style=solid
// route=orthogonal
// from=west
// to=east
// fromCardinality=one
// toCardinality=one
// via=(1586,1338),(1586,1482),(1514,1482)

// @group 0ttxdgu
// label=Bancas
// labelX=52
// labelY=26
// x=104
// y=1066
// width=962
// height=286
// background=#3B0764
// border=#A855F7
// text=#A855F7
// opacity=0.02
// tableBackground=#111827
// tableBorder=#9333EA
// tableHeader=#7E22CE
// tableText=#F8FAFC
// tableLine=#2dd4bf
// tableOpacity=1

// @group fkf7znh
// label=New Group
// labelX=52
// labelY=26
// x=598
// y=1768
// width=1456
// height=312
// background=#064E3B
// border=#10B981
// text=#10B981
// opacity=0.02
// tableBackground=#111827
// tableBorder=#059669
// tableHeader=#047857
// tableText=#F8FAFC
// tableLine=#2dd4bf
// tableOpacity=1

// @group uyvqwj3
// label=Relatorios
// labelX=52
// labelY=26
// x=1092
// y=1066
// width=962
// height=676
// background=#451A03
// border=#F59E0B
// text=#F59E0B
// opacity=0.02
// tableBackground=#111827
// tableBorder=#D97706
// tableHeader=#B45309
// tableText=#F8FAFC
// tableLine=#374342
// tableOpacity=0.95

// @group ahnhf2y
// label=New Group
// labelX=52
// labelY=26
// x=104
// y=1378
// width=962
// height=364
// background=#172554
// border=#3B82F6
// text=#3B82F6
// opacity=0.02
// tableBackground=#111827
// tableBorder=#2563EB
// tableHeader=#1D4ED8
// tableText=#F8FAFC
// tableLine=#2dd4bf
// tableOpacity=1

// @group eclm489
// label=New Group
// labelX=52
// labelY=26
// x=598
// y=2106
// width=1456
// height=390
// background=#164E63
// border=#06B6D4
// text=#06B6D4
// opacity=0.02
// tableBackground=#111827
// tableBorder=#0891B2
// tableHeader=#0E7490
// tableText=#F8FAFC
// tableLine=#2dd4bf
// tableOpacity=1

// @group j0b37ft
// label=New Group
// labelX=52
// labelY=26
// x=104
// y=1768
// width=468
// height=312
// background=#312E81
// border=#6366F1
// text=#6366F1
// opacity=0.02
// tableBackground=#111827
// tableBorder=#4F46E5
// tableHeader=#4338CA
// tableText=#F8FAFC
// tableLine=#2dd4bf
// tableOpacity=1

// @group 5hw3f2d
// label=New Group
// labelX=52
// labelY=26
// x=104
// y=2106
// width=468
// height=390
// background=#4C0519
// border=#F43F5E
// text=#F43F5E
// opacity=0.02
// tableBackground=#111827
// tableBorder=#E11D48
// tableHeader=#BE123C
// tableText=#F8FAFC
// tableLine=#2dd4bf
// tableOpacity=1
