Table user {
  id_user int [pk]
  name varchar(255) [not null]
  email varchar(255) [not null, unique]
}

Table project {
  id_project int [pk]
  name varchar(255) [not null]
  description text
  created_by_user_id int [not null]
}

Table technology {
  id_technology int [pk]
  name varchar(100) [not null, unique]
  slug varchar(100) [not null, unique]
  created_by_user_id int
}

Table project_stack {
  id_project int [pk]
  id_technology int [pk]
  indexes {
    (id_project, id_technology) [pk]
  }
}

Ref: project.created_by_user_id > user.id_user

Ref: technology.created_by_user_id > user.id_user

Ref: project_stack.id_project > project.id_project

Ref: project_stack.id_technology > technology.id_technology
