Table usuario {
  id int [pk]
  nome varchar(100) [not null]
  email varchar(150) [not null, unique]
  senha varchar(255) [not null]
  criado_em timestamp [not null, default: CURRENT_TIMESTAMP]
}

Table carro {
  id int [pk]
  marca varchar(50) [not null]
  modelo varchar(80) [not null]
  ano int [not null]
  usuario_id int
}

Ref: carro.usuario_id > usuario.id
