Table ages_user {
  id uuid [pk]
  email varchar(255) [not null]
  pucrs_id char(8) [not null]
  name varchar(255) [not null]
  password varchar(255) [not null]
  image_url varchar(255)
  course course [not null]
  type user_type [not null]
}

Table project {
  id uuid [pk]
  description text [not null]
  git_lab varchar(255)
  name varchar(255) [not null]
  active boolean [not null]
  group_photo_url varchar(255)
  year int [not null]
  semester semester [not null]
  logo_url varchar(255)
}

Table team {
  id uuid [pk]
  teacher_id uuid [not null]
  project_id uuid [not null]
}

Table class {
  id uuid [pk]
  number int [not null]
  year int [not null]
  semester semester [not null]
  teacher_id uuid [not null]
  active boolean [not null]
}

Table semester_profile {
  id uuid [pk]
  grade numeric(4,2)
  ages_role ages_role [not null]
  student_status semester_status [not null]
  user_id uuid [not null]
  team_id uuid [not null]
  class_id uuid [not null]
}

Table lesson {
  id uuid [pk]
  date timestamp [not null]
  class_id uuid [not null]
}

Table otp {
  id uuid [pk]
  user_id uuid [not null]
  expires_at timestamp [not null]
  token varchar(255) [not null]
  used boolean [not null]
}

Table schedule {
  id uuid [pk]
  admin_id uuid [not null]
  event char(10) [not null]
  event_date timestamp [not null]
  event_period char(10) [not null]
  event_time time(0) [not null]
}

Table technology {
  id uuid [pk]
  name varchar(255) [not null]
  type technology_type [not null]
}

Table project_stack {
  id uuid [pk]
  project_id uuid [not null]
  technology_id uuid [not null]
  indexes {
    (project_id, technology_id) [unique]
  }
}

Table report {
  id uuid [pk]
  student_id uuid [not null]
  create_date timestamp [not null]
  edit_date timestamp [not null]
  grade numeric(4,2)
  type report_type [not null]
  url_archive varchar(255)
  comment text
  correction_url varchar(255)
  revision_date timestamp
}

Table examining_board {
  id uuid [pk]
  date date [not null]
  grade numeric(4,2) [not null]
  room varchar(255) [not null]
  student_id uuid [not null]
}

Table examining_board_member {
  id uuid [pk]
  examining_board_id uuid [not null]
  teacher_id uuid [not null]
}

Table attendance {
  id uuid [pk]
  lesson_id uuid [not null]
  student_id uuid [not null]
}

Table sprint_report {
  id uuid [pk]
  activity_completed text [not null]
  learned_lessons text [not null]
  next_steps text [not null]
  predicted_activity text [not null]
  problems_encountered text [not null]
  sprint sprint [not null]
  report_id uuid [not null, unique]
}

Table hours_report {
  id uuid [pk]
  activities text
  entry_time timestamp [not null]
  exit_time timestamp
  rejection_justification text
  approved boolean [not null]
  report_id uuid [not null, unique]
}

Ref: team.teacher_id > ages_user.id

Ref: team.project_id > project.id

Ref: class.teacher_id > ages_user.id

Ref: semester_profile.user_id > ages_user.id

Ref: semester_profile.team_id > team.id

Ref: semester_profile.class_id > class.id

Ref: lesson.class_id > class.id

Ref: otp.user_id > ages_user.id

Ref: schedule.admin_id > ages_user.id

Ref: project_stack.project_id > project.id

Ref: project_stack.technology_id > technology.id

Ref: report.student_id > semester_profile.id

Ref: examining_board.student_id > semester_profile.id

Ref: examining_board_member.examining_board_id > examining_board.id

Ref: examining_board_member.teacher_id > ages_user.id

Ref: attendance.lesson_id > lesson.id

Ref: attendance.student_id > semester_profile.id

Ref: sprint_report.report_id > report.id

Ref: hours_report.report_id > report.id
